# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b3af30b31804d1fee0164992b9fbe433c919faebf3ade42359aeb484cf8f18dca9300504197c496bfb36fa3c17349fb4d97f989528ee4751e605c1a9498e27

test:
  secret_key_base: 94d412d1446734ea29d105f9ef27bb316b1a8679cc5ec2541333d93398b1da9459582c02d630d6e90d7d606a102305d15d425b4b64582f4025aaf3aa4781e1ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
